# Generated by Django 3.1.5 on 2024-05-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='allowed_attempts',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='due',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='time_limit_mins',
        ),
    ]
