# Generated by Django 3.1.5 on 2024-05-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20240506_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempter',
            name='completed',
        ),
        migrations.AddField(
            model_name='attempter',
            name='test_completed',
            field=models.BooleanField(default=False),
        ),
    ]
