# Generated by Django 3.1.5 on 2024-06-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20240508_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='points_to_pass',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
