# Generated by Django 3.1.5 on 2024-04-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='hours',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
