# Generated by Django 3.1.5 on 2024-04-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_module_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='hours',
        ),
    ]
