# Generated by Django 3.1.5 on 2024-04-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_remove_module_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
