# Generated by Django 3.1.5 on 2024-05-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_module_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='hours',
        ),
    ]
