# Generated by Django 3.1.5 on 2024-05-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_remove_module_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='quizzes',
        ),
    ]
