# Generated by Django 3.1.5 on 2024-05-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_remove_profile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
