# Generated by Django 3.1.5 on 2024-05-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_delete_usercourses'),
        ('authy', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(to='classroom.Course'),
        ),
    ]
