# Generated by Django 3.1.5 on 2024-05-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_profile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
    ]
