# Generated by Django 3.1.5 on 2024-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_remove_profile_courses'),
        ('learningcontrol', '0003_assignedcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_courses',
            field=models.ManyToManyField(to='learningcontrol.AssignedCourses'),
        ),
    ]
