# Generated by Django 3.1.5 on 2024-05-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0006_profile_assigned_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
