# Generated by Django 3.1.5 on 2024-06-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningcontrol', '0006_auto_20240514_2246'),
        ('authy', '0008_auto_20240612_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, null=True, to='learningcontrol.AssignedCourses'),
        ),
    ]
