# Generated by Django 3.1.5 on 2024-05-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningcontrol', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourses',
        ),
    ]
