# Generated by Django 3.1.5 on 2024-05-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0011_delete_usercourses'),
        ('learningcontrol', '0002_delete_usercourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.course')),
            ],
        ),
    ]
