# Generated by Django 3.1.5 on 2024-05-10 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learningcontrol', '0003_assignedcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcourses',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
