# Generated by Django 3.1.5 on 2024-05-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningcontrol', '0004_assignedcourses_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcourses',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
