# Generated by Django 3.1.5 on 2024-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningcontrol', '0005_assignedcourses_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcourses',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedcourses',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
