# Generated by Django 3.1.5 on 2024-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('classroom', '0005_course_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quizzes',
            field=models.ManyToManyField(to='quiz.Quizzes'),
        ),
    ]
