# Generated by Django 3.1.5 on 2024-05-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_usercourses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourses',
        ),
    ]
