# Generated by Django 3.1.5 on 2024-06-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_delete_usercourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolled',
        ),
    ]
